use_frameworks!

target 'OpenSSL-lib-iOS_Example' do
  pod 'OpenSSL-lib-iOS', :path => '../'

  target 'OpenSSL-lib-iOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
